http.host: "0.0.0.0"
# Ruta a la configuración del pipeline
path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

#Para no tener problemas con el proxy
#xpack.security.enabled: true
